- name: Run app on EC2
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      cd /home/ubuntu/app
      sudo cp -r * /var/www/html/
      sudo systemctl reload nginx